import type { Metadata } from "next";
import { Cormorant_Garamond, Karla } from "next/font/google";
import "./globals.css";

const cormorant = Cormorant_Garamond({ 
  subsets: ["latin"], 
  weight: "400", 
  variable: '--font-cormorant' 
});

const karla = Karla({ 
  subsets: ["latin"], 
  weight: "400", 
  variable: '--font-karla' 
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${cormorant.variable} ${karla.variable}`}>
      <body className="font-sans">
        {children}
      </body>
    </html>
  );
}
