import type { Metadata } from "next";
import { Cormorant_Garamond, Karla } from "next/font/google";
import CookieConsent from "react-cookie-consent";
import "./globals.css";
import CookieBanner from "@/components/CookieBanner";

const cormorant = Cormorant_Garamond({ 
  subsets: ["latin"], 
  weight: "400", 
  variable: '--font-cormorant' 
});

const karla = Karla({ 
  subsets: ["latin"], 
  weight: "400", 
  variable: '--font-karla' 
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function MainLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" className={`${cormorant.variable} ${karla.variable}`}>
      <body className="font-sans">
        {children}
        <CookieBanner />
      </body>
    </html>
  );
}